<?php

namespace WTS_EAE\Pro\Modules\RadialCharts;

use WTS_EAE\Base\Module_Base;

class Module extends Module_Base {

	public function get_widgets() {
		return [
			'RadialCharts',
		];
	}

	public function get_name() {
		return 'eae-radial-charts';
	}

	public function get_title() {

		return __( 'Radial Charts', 'wts-eae' );
	}

	public function add_dependent_js_css() {
		parent::add_dependent_js_css(); // TODO: Change the autogenerated stub
		wp_enqueue_style( 'font-awesome-4-shim' );
		wp_enqueue_style( 'font-awesome-5-all' );
		wp_enqueue_script( 'font-awesome-4-shim' );
	}

}
